scope: ["https://spreadsheets.google.com/feeds", 'https://www.googleapis.com/auth/spreadsheets',
                      "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]
creds: keys.json

resourcesPath: resources/
keysPath: keys/
databasePath: database/
clubsPath: clubs/
mistersPath: misters/
nameDatabase: Quiniela 21-22
nameDownloadedDatabase: database
extensionDatabase: .xlsx
extensionImage: .png

maxClubsSantander: 20
maxClubsSmartbank: 22
firstRowSantander: 3
firstRowSmartbank: 25
maxGamesSantander: 38
maxGamesSmartbank: 42
lastColPointsSantander: 46
lastColPointsSmartbank: 48
firstColPoints: 7
initPoints: 100

minimumWidthWindow: 1460
minimumHeightWindow: 960
imageWidth: 82.64
imageHeight: 82.64
buttonClubHeight: 140
buttonClubWidth: 70

misterPosHeight: 111
misterPosStart: -1
misterIncrement: 1.5
misterNearIncrement: -3
arrowX: 0
arrowY: -5
arrowHeadWidth: 0.5 
arrowHeadLength: 1
arrowHeight: 106
arrowIncrement: 0.45

verySmallZoom: 0.2
smallZoom: 0.3
mediumZoom: 0.4
highZoom: 0.7

formatDelayedAndPlayed: APLZ J
formatDelayed: APLZ
formatAhead: ADL J