scope: ["https://spreadsheets.google.com/feeds", 'https://www.googleapis.com/auth/spreadsheets',
                      "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]
creds: keys.json

path: /home/alvaro/github/LaLigaEstadisticas/LaLigaEstadisticas/src/main/
resourcesPath: resources/
keysPath: keys/
databasePath: database/
nameDatabase: Quiniela 21-22
nameDownloadedDatabase: Quiniela Script
extensionDatabase: .xlsx
extensionImage: .png

maxClubsSantander: 20
maxClubsSmartbank: 22
firstRowSantander: 3
firstRowSmartbank: 25
maxGamesSantander: 38
maxGamesSmartbank: 42
lastColPointsSantander: 46
lastColPointsSmartbank: 48
firstColPoints: 7
initPoints: 100

minimumWidthWindow: 1460
minimumHeightWindow: 960
imageWidth: 82.64
imageHeight: 82.64
buttonClubHeight: 140
buttonClubWidth: 70

formatDelayedAndPlayed: APLZ J
formatDelayed: APLZ